image: maven:3-openjdk-17

stages: 
  - lint  
  - build
  - test

build-job:      
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn package
    - echo "Compile complete"
  artifacts:
    name: "Learning"
    when: on_success
    expire_in: "30 days"
    paths:
      - "distro/target/distro-*.jar"

unit-test-job:  
  stage: test   
  script:
    - echo "Running unit tests..."
    - mvn test
    - echo "Unit tests complete."

lint-test-job:  
  stage: lint   
  script:
    - echo "Linting code..."
    - mvn clean install validate
    - echo "Linter finished"
