stages:          
  - build
  - test

build-job:      
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn clean install
    - echo "Compile complete."

unit-test-job:  
  stage: test   
  script:
    - echo "Running unit tests..."
    - mvn test
    - echo "Unit tests complete."

lint-test-job:  
  stage: test   
  script:
    - echo "Linting code..."
    - mvn validate
    - echo "Linter finished"
