image: maven:3-openjdk-17

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages: 
  - lint  
  - test
  - build

create-and-publish-docker-image:      
  stage: build
  services:
    - name: docker:20.10.16-dind
      alias: docker
  script:
    - echo "Loggin into Registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Compiling the code, building docker image and publishing..."
    - mvn package -Dspring-boot.build-image.publish=$publishDockerImage
    - echo "Maven Package complete"
  artifacts:
    name: "Learning"
    when: on_success
    expire_in: "30 days"
    paths:
      - "distro/target/distro-*.jar"

unit-test-job:  
  stage: test   
  script:
    - echo "Running unit tests..."
    - mvn test
    - echo "Unit tests complete."

lint-test-job:  
  stage: lint   
  script:
    - echo "Linting code..."
    - mvn clean install validate
    - echo "Linter finished"
